baseURL = "https://2kabhishek.github.io/blog/"
title = "2KAbhishek Blogs"
copyright = "©2024 2KAbhishek"

languageCode = "en"
hasCJKLanguage = true
defaultContentLanguage = "en"

enableRobotsTXT = true
[pagination]
  pagerSize = 7  # number of articles per page
enableEmoji = true

# Enable Disqus
# [config.services.disqus]
#   shortname = "2kabhishek"

[module]
  [[module.imports]]
    path = "github.com/2kabhishek/neonote"

[author]
  name = "2KAbhishek"
  email = "iam2kabhishek@gmail.com"

[params]
  author = "2KAbhishek"
  description = "2KAbhishek Blogs"
  style = "auto"  # auto, light, dark
  logo = "https://avatars.githubusercontent.com/u/25423853?v=4"
  slogan = ""

# Declare custom css here
[params.assets]
  css = ["css/fonts.css", "css/custom.css"]

[params.comments]
  enable = false  # En/Disable comments, You can also enable comments on per page.

[params.math]
  enable = false # Load math globally, You can also enable math on per page.
  use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.nav]
  showCategories = false
  showTags = false

# You can add taxonomies here, then link new pages in [[params.nav.custom]]
[taxonomies]
  category = "categories"
  tag = "tags"

[[params.nav.custom]]
  title = "Index"
  url = "/"

[[params.nav.custom]]
  title = "Tags"
  url = "/tags/"

[[params.nav.custom]]
  title = "Archives"
  url = "/archives/"

[[params.nav.custom]]
  title = "About"
  url = "/about/"

# Chroma highlight
[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = true
  style = "dracula"

[markup.goldmark.renderer]
  unsafe = true #enable raw HTML in Markdown

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

[permalinks]
  post = "/:year/:month/:title/"

[minify]
  # Deploy with --minify command to minify assets
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 1
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 1
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 1
    [minify.tdewolff.xml]
      keepWhitespace = false
