baseURL = "https://2kabhishek.github.io/hugo-neovimium/"
title = "Neovimium"
theme = "hugo-neovimium"
themesdir = "../.."
copyright = "©2022 Neovimium"

languageCode = "en"  # for the rss generation. See https://github.com/gohugoio/hugo/issues/349
defaultContentLanguage = "en"  # for the site language. Use Hugo i18n configuration
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "dracula"

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[mediaTypes]
[mediaTypes."text/toml"]
suffixes = ["toml"]

[outputFormats]
[outputFormats.TOML]
mediaType = "text/toml"

[outputs]
  home = ["HTML", "RSS", "TOML"]

[minify]
# Need Hugo version v0.68.0+
# Newer Hugo version may fix some minify issues. So if you want to use this function, use lastest Hugo for a better experience.
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = true
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 1
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 1
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 1
    [minify.tdewolff.xml]
      keepWhitespace = false

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = ""
keywords = "blog, theme, minimalist"
description = "Hugo neovimium theme, a minimalist theme for bloggers"
author = "2kabhishek"

ShowOutdatedOnPosts = true  # Add a prompt box before a post if the post published long ago
OutdatedDays = 730  # Collaborate with preceding params. If a post is edited before this params,
	       	    # a prompt box will appear before the post

[params.assets]
css = ["css/fonts.css"]

# Disqus comments system
[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.


[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[taxonomies]
  category = "categories"
  tag = "tags"
  search = "search"

[[params.nav.custom]]
title = "Tags"
url = "/tags/"

[[params.nav.custom]]
title = "Archives"
url = "/archives/"

[[params.nav.custom]]
title = "Search"
url = "/search/"

[[params.nav.custom]]
title = "About"
url = "/about/"

[[params.nav.custom]]
title = "Hugo"
url = "https://gohugo.io/"
