baseURL = "https://2kabhishek.github.io/neonote/"
title = "Neonote"
theme = "neonote"
themesdir = "../.."
copyright = "©2024 Neonote"

languageCode = "en"  # for the rss generation. See https://github.com/gohugoio/hugo/issues/349
defaultContentLanguage = "en"  # for the site language. Use Hugo i18n configuration
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
[config.services.disqus]
  shortname = "2kabhishek"

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = true
  style = "dracula"

[markup.goldmark.renderer]
  unsafe = true  # enable raw HTML in Markdown

[mediaTypes]
[mediaTypes."text/toml"]
  suffixes = ["toml"]

[outputFormats]
[outputFormats.TOML]
  mediaType = "text/toml"

[outputs]
  home = ["HTML", "RSS", "TOML"]

[params.author]
  name = "2kabhishek"
  email = "iam2kabhishek@gmail.com"

[params]
  style = "auto"
  logo = ""
  keywords = "blog, theme, minimalist"
  description = "Hugo neonote theme, a minimalist theme for bloggers"
  slogan = "A minimalist theme for bloggers"

ShowOutdatedOnPosts = true  # Add a prompt box before a post if the post published long ago
OutdatedDays = 730  # Collaborate with preceding params. If a post is edited before this params, a prompt box will appear before the post

# Disqus comments system
[params.comments]
  enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

# Another comments system that using github discussion. See detail in https://giscus.app
# Conflict with Disqus
# TODO: auto change light/dark theme when the whole site is setting auto-theme
[params.giscus]
  enable = true
  repo = "2kabhishek/neonote"
  repoID = "some-repo-id"
  category = "Announcements"
  categoryID = "some-category-id"
  dataTheme = "dark"
  dataLang = "en"

[params.utterances]
  enable = true
  repo = "2kabhishek/neonote"
  issueTerm = "pathname"
  theme = "preferred-color-scheme"
  crossorigin = "anonymous"

[params.math]
  enable = false # load math globally, default: false. You can always enable math on per page.
  use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.nav]
  showCategories = false
  showTags = true

[taxonomies]
  category = "categories"
  tag = "tags"

[[params.nav.custom]]
  title = "Archives"
  url = "/neonote/archives"

[[params.nav.custom]]
  title = "About"
  url = "/neonote/about"

[[params.nav.custom]]
  title = "Hugo"
  url = "https://gohugo.io/"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = true
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 1
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 1
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 1
    [minify.tdewolff.xml]
      keepWhitespace = false
